services:
  - type: web
    name: campusalert
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn campusalert.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: MONGODB_URI
        sync: false
